#ifndef CJAVA_H
#define CJAVA_H

#define NOT_THE_CJAVA_HEADER

#define CJAVA_GUI 2
#define CJAVA_CLI 3

#define CJAVA_SUBSYSTEM(SYSTEM)
#define CJAVA_SIZE_OF_IMAGE(IMGSIZE)
#define CJAVA_IMPORT_FUNC(NAME, DLL)
#define CJAVA_PUT_FILE(IDX, PATH)
#define CJAVA_GET_POINTER_TO_FILE(IDX)
#define CJAVA_GET_FILE_LENGTH(IDX)

#endif